### ISSUE TITLE
Compatibility with Shopware 6.5

### ISSUE THREAD

**Issue by janobi** [mapp-digital/shopware-plugin#1]
Could you please update for compatibility with Shopware 6.5? The plugin uses `Shopware\Core\Framework\Event\BusinessEvents::GLOBAL_EVENT` which was removed here: https://github.com/shopware/platform/commit/6fef82f462ee34d2e78fc4aaf8d2d280a3b347fa

Thanks!

**Comment by StephanGuenther** [comment]
Shopware 6.5 is supported as of version 0.0.6
